services:
  timestamp-temperature-bot:
    image: ghcr.io/wissididom/temperature-conversion-integration
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file:
      - .env
